// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "app/internal/features/auth/delivery/http/dto"
	entity "app/internal/shared/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "app/internal/features/auth/usecase"
)

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockAuthUsecase) Login(ctx context.Context, req dto.LoginRequest) (*usecase.LoginResponse, int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *usecase.LoginResponse
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) (*usecase.LoginResponse, int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) *usecase.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginRequest) int); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.LoginRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.LoginRequest
func (_e *MockAuthUsecase_Expecter) Login(ctx interface{}, req interface{}) *MockAuthUsecase_Login_Call {
	return &MockAuthUsecase_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthUsecase_Login_Call) Run(run func(ctx context.Context, req dto.LoginRequest)) *MockAuthUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.LoginRequest))
	})
	return _c
}

func (_c *MockAuthUsecase_Login_Call) Return(_a0 *usecase.LoginResponse, _a1 int, _a2 error) *MockAuthUsecase_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthUsecase_Login_Call) RunAndReturn(run func(context.Context, dto.LoginRequest) (*usecase.LoginResponse, int, error)) *MockAuthUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockAuthUsecase) Register(ctx context.Context, req dto.RegisterRequest) (*entity.User, int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *entity.User
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest) (*entity.User, int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest) *entity.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterRequest) int); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.RegisterRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.RegisterRequest
func (_e *MockAuthUsecase_Expecter) Register(ctx interface{}, req interface{}) *MockAuthUsecase_Register_Call {
	return &MockAuthUsecase_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAuthUsecase_Register_Call) Run(run func(ctx context.Context, req dto.RegisterRequest)) *MockAuthUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.RegisterRequest))
	})
	return _c
}

func (_c *MockAuthUsecase_Register_Call) Return(_a0 *entity.User, _a1 int, _a2 error) *MockAuthUsecase_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthUsecase_Register_Call) RunAndReturn(run func(context.Context, dto.RegisterRequest) (*entity.User, int, error)) *MockAuthUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
