// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "app/internal/features/user/delivery/http/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"

	pkg "app/pkg"
)

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *MockUserUsecase) GetProfile(ctx context.Context, userID string) (*dto.UserResponse, int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *dto.UserResponse
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.UserResponse, int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.UserResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserUsecase_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockUserUsecase_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserUsecase_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockUserUsecase_GetProfile_Call {
	return &MockUserUsecase_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockUserUsecase_GetProfile_Call) Run(run func(ctx context.Context, userID string)) *MockUserUsecase_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserUsecase_GetProfile_Call) Return(_a0 *dto.UserResponse, _a1 int, _a2 error) *MockUserUsecase_GetProfile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserUsecase_GetProfile_Call) RunAndReturn(run func(context.Context, string) (*dto.UserResponse, int, error)) *MockUserUsecase_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx, queries
func (_m *MockUserUsecase) GetUsers(ctx context.Context, queries map[string]string) ([]*dto.UserResponse, pkg.PaginationResponse, int, error) {
	ret := _m.Called(ctx, queries)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*dto.UserResponse
	var r1 pkg.PaginationResponse
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) ([]*dto.UserResponse, pkg.PaginationResponse, int, error)); ok {
		return rf(ctx, queries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) []*dto.UserResponse); ok {
		r0 = rf(ctx, queries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) pkg.PaginationResponse); ok {
		r1 = rf(ctx, queries)
	} else {
		r1 = ret.Get(1).(pkg.PaginationResponse)
	}

	if rf, ok := ret.Get(2).(func(context.Context, map[string]string) int); ok {
		r2 = rf(ctx, queries)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, map[string]string) error); ok {
		r3 = rf(ctx, queries)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserUsecase_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserUsecase_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - queries map[string]string
func (_e *MockUserUsecase_Expecter) GetUsers(ctx interface{}, queries interface{}) *MockUserUsecase_GetUsers_Call {
	return &MockUserUsecase_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, queries)}
}

func (_c *MockUserUsecase_GetUsers_Call) Run(run func(ctx context.Context, queries map[string]string)) *MockUserUsecase_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockUserUsecase_GetUsers_Call) Return(_a0 []*dto.UserResponse, _a1 pkg.PaginationResponse, _a2 int, _a3 error) *MockUserUsecase_GetUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockUserUsecase_GetUsers_Call) RunAndReturn(run func(context.Context, map[string]string) ([]*dto.UserResponse, pkg.PaginationResponse, int, error)) *MockUserUsecase_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *MockUserUsecase) UpdateProfile(ctx context.Context, userID string, req *dto.UpdateProfileRequest) (*dto.UserResponse, int, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *dto.UserResponse
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateProfileRequest) (*dto.UserResponse, int, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateProfileRequest) *dto.UserResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateProfileRequest) int); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *dto.UpdateProfileRequest) error); ok {
		r2 = rf(ctx, userID, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserUsecase_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserUsecase_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *dto.UpdateProfileRequest
func (_e *MockUserUsecase_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockUserUsecase_UpdateProfile_Call {
	return &MockUserUsecase_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockUserUsecase_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, req *dto.UpdateProfileRequest)) *MockUserUsecase_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.UpdateProfileRequest))
	})
	return _c
}

func (_c *MockUserUsecase_UpdateProfile_Call) Return(_a0 *dto.UserResponse, _a1 int, _a2 error) *MockUserUsecase_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserUsecase_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, *dto.UpdateProfileRequest) (*dto.UserResponse, int, error)) *MockUserUsecase_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
